# Generated by Django 3.1.5 on 2021-03-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date_created',
            field=models.DateField(null=True),
        ),
    ]
