# Generated by Django 3.1.5 on 2021-03-29 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20210329_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_entry',
            field=models.TextField(default=django.utils.timezone.now, null=True),
        ),
    ]
