# Generated by Django 3.1.5 on 2021-03-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20210330_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
