# Generated by Django 3.1.5 on 2021-04-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20210331_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date_created',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
