# Generated by Django 3.1.5 on 2021-04-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_auto_20210402_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
