# Generated by Django 3.1.5 on 2021-04-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_diary_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
